name: Build Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:

          - name: Checkout demo
            uses: actions/checkout@v4

          - name: Checkout LB Planner plugin
            uses: actions/checkout@v4
            with:
              repository: necodeIT/lb_planner_plugin
              path: lb_planner_plugin

          - name: 🐳 Login to GitHub Container Registry
            uses: docker/login-action@v3.3.0
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
  
          - name: 🐳 Build and Push
            uses: docker/build-push-action@v6.10.0
            with:
              context: .
              file: ./Dockerfile
              build-contexts: |
                lbplanner=./lb_planner_plugin
              platforms: linux/amd64
              push: true
              tags: ghcr.io/necodeit/eduplanner_demo:latest
